### ISSUE TITLE
Feature: add ability to use key.bin file to extract

### ISSUE THREAD

**Issue by webbedspace** [HNIdesu/SRPGStudioReverseTools#1]
[srpg-studio-extractor-0.1](https://github.com/godoway/SRPG-Studio-extractor/releases/tag/0.1) has a `key.bin` file included, which can be used to decrypt data.dts files with unknown passwords. Could this functionality be added to these scripts?

**Comment by HNIdesu** [comment]
Actually, I'm not entirely sure if it works in the context you've mentioned, as we have used quite different methods to decrypt the files. In my experience, I have reversed some games and found that their passwords are all "key",so I set that as the default password.
I would greatly appreciate it if you could provide some sample files that cannot be decrypted by the current script. This would help in understanding the issue better and potentially adding the requested functionality.
